const schemesData = [
  { id: "mahadbt", mr: "महाडीबीटी पोर्टल (अर्ज एक - योजना अनेक)", en: "MahaDBT Portal (Single Window Scheme)", emoji: "🚀", pdf: "https://mahadbt.maharashtra.gov.in/Farmer/AgriLogin/AgriLogin" },
  { id: "helpdesk", mr: "महाडीबीटी हेल्पडेस्क", en: "MahaDBT Helpdesk", emoji: "☎️", pdf: "#" },
  { id: "mahavistaar", mr: "महाविस्तार (MahaVISTAAR-AI APP)", en: "MahaVISTAAR-AI App", emoji: "📱", pdf: "#" },
  { id: "nanaji", mr: "नानाजी देशमुख कृषी संजीवनी प्रकल्प टप्पा - २", en: "Nanaji Deshmukh Krishi Sanjivani Project Phase-2", emoji: "🌱", pdf: "#" },
  { id: "samruddhi", mr: "कृषी समृद्धी योजना (BBF, शेततळे, ड्रोन)", en: "Krishi Samruddhi Scheme (BBF, Farm Pond, Drone)", emoji: "🚜", pdf: "#" },
  { id: "natural-farming", mr: "राष्ट्रीय नैसर्गिक शेती अभियान", en: "National Natural Farming Mission", emoji: "🌿", pdf: "#" },
  { id: "smart", mr: "मा. बाळासाहेब ठाकरे कृषी व्यवसाय व ग्रामीण परिवर्तन प्रकल्प (SMART)", en: "Balasaheb Thackeray Agribusiness & Rural Transformation Project (SMART)", emoji: "📈", pdf: "#" },
  { id: "crop-insurance", mr: "सुधारीत प्रधानमंत्री पीक विमा योजना", en: "Revised Pradhan Mantri Fasal Bima Yojana", emoji: "🛡️", pdf: "#" },
  { id: "hort-insurance", mr: "फळपीक विमा योजना सन २०२४-२५ ते २०२५-२६", en: "Horticulture Crop Insurance Scheme 2024-26", emoji: "🍎", pdf: "#" },
  { id: "crop-comp", mr: "पीक स्पर्धा", en: "Crop Competition", emoji: "🏆", pdf: "#" },
  { id: "tours", mr: "राज्यातील शेतकऱ्यांचे देशाबाहेर अभ्यास दौरे", en: "International Study Tours for Farmers", emoji: "✈️", pdf: "#" },
  { id: "orchard", mr: "फळबाग व इतर पिके लागवड", en: "Orchard & Other Crop Cultivation", emoji: "🌳", pdf: "#" },
  { id: "calc", mr: "अंदाजपत्रके व कॅल्क्युलेटर्स (Estimates & Calculators)", en: "Estimates & Calculators", emoji: "🧮", pdf: "#" },
  { id: "veg-seed", mr: "भाजीपाला व मसाला बियाणे उत्पादन अनुदान", en: "Vegetable & Spice Seed Production Subsidy", emoji: "🧅", pdf: "#" },
  { id: "nursery", mr: "रोपवाटिका स्थापन करणेसाठी अनुदान", en: "Nursery Establishment Subsidy", emoji: "🪴", pdf: "#" },
  { id: "tissue", mr: "नवीन उतीसंवर्धन प्रयोगशाळा स्थापना", en: "New Tissue Culture Laboratory Setup", emoji: "🔬", pdf: "#" },
  { id: "tracenet", mr: "निर्यातक्षम फळे व भाजीपाला ट्रेसीबीलीटीनेट नोंदणी", en: "TraceNet Registration for Exportable Fruits & Vegetables", emoji: "📦", pdf: "#" },
  { id: "aif", mr: "AIF- कृषी पायाभूत सुविधा निधी अंतर्गत वित्त पुरवठा", en: "Agriculture Infrastructure Fund (AIF) Financing", emoji: "💰", pdf: "#" },
  { id: "pmfme", mr: "प्रधानमंत्री सूक्ष्म खाद्य प्रक्रिया उन्नयन योजना (PMFME)", en: "PM Formalization of Micro Food Processing Enterprises (PMFME)", emoji: "🏭", pdf: "#" },
  { id: "cm-food", mr: "मुख्यमंत्री कृषी व अन्न प्रक्रिया योजना", en: "Chief Minister Agriculture & Food Processing Scheme", emoji: "🌾", pdf: "#" },
  { id: "ahilyadevi", mr: "पुण्यश्लोक अहिल्यादेवी होळकर रोपवाटिका योजना", en: "Punyashlok Ahilyadevi Holkar Nursery Scheme", emoji: "🌻", pdf: "#" },
  { id: "school", mr: "शेतीशाळा", en: "Farmers Field School (FFS)", emoji: "🏫", pdf: "#" },
  { id: "well", mr: "विहीर (राकृवियो व मग्रारोहयो अंतर्गत)", en: "Agricultural Well Construction (RKVY & MGNREGS)", emoji: "💧", pdf: "#" },
  { id: "ambedkar", mr: "डॉ. बाबासाहेब आंबेडकर कृषी स्वावलंबन योजना", en: "Dr. Babasaheb Ambedkar Krishi Swavalamban Yojana", emoji: "🏡", pdf: "#" },
  { id: "birsa", mr: "बिरसा मुंडा कृषि क्रांती योजना", en: "Birsa Munda Krishi Kranti Yojana", emoji: "🏹", pdf: "#" },
  { id: "ponds", mr: "शेततळे व अस्तरीकरण", en: "Farm Pond & Plastic Lining", emoji: "🏞️", pdf: "#" },
  { id: "drip", mr: "ठिबक व तुषार सिंचन अनुदान", en: "Drip & Sprinkler Irrigation Subsidy", emoji: "🚿", pdf: "#" },
  { id: "tractor", mr: "ट्रॅक्टर व इतर शेती औजारे", en: "Tractor & Farm Implements Subsidy", emoji: "🚜", pdf: "#" },
  { id: "drone", mr: "ड्रोन व नमो ड्रोन दिदी मार्गदर्शक सूचना", en: "Drone & Namo Drone Didi Guidelines", emoji: "🛸", pdf: "#" },
  { id: "pump", mr: "पंपसंच व पाईप लाईन अनुदान", en: "Pump Set & Pipeline Subsidy", emoji: "🔌", pdf: "#" },
  { id: "sericulture", mr: "रेशीम उद्योग विकास योजना", en: "Sericulture Industry Development Scheme", emoji: "🐛", pdf: "#" },
  { id: "bee", mr: "मधुमक्षिका पालन प्रकल्प", en: "Beekeeping Project", emoji: "🐝", pdf: "#" },
  { id: "mushroom", mr: "अळिंबी उत्पादन प्रकल्प", en: "Mushroom Cultivation Project", emoji: "🍄", pdf: "#" },
  { id: "greenhouse", mr: "हरितगृह व शेडनेट हाऊस", en: "Greenhouse & Shade Net House", emoji: "🏡", pdf: "#" },
  { id: "mill", mr: "मिनी दाल मिल व राईस मिल", en: "Mini Dal Mill & Rice Mill", emoji: "⚙️", pdf: "#" },
  { id: "seed-unit", mr: "बीज प्रक्रिया युनिट व गोदाम बांधकाम", en: "Seed Processing Unit & Godown Construction", emoji: "🏛️", pdf: "#" },
  { id: "pm-kisan", mr: "प्रधानमंत्री किसान सन्मान निधी व मानधन योजना", en: "PM-KISAN & Samman Nidhi Scheme", emoji: "💳", pdf: "#" },
  { id: "gopinath-munde", mr: "गोपीनाथ मुंडे शेतकरी अपघात सुरक्षा सानुग्रह अनुदान योजना", en: "Gopinath Munde Farmers Accident Insurance Scheme", emoji: "⛑️", desc: "शेती व्यवसाय करताना होणारे अपघात, नैसर्गिक आपत्तीमुळे होणाऱ्या अपघातांसाठी आर्थिक लाभ देणारी योजना.", pdf: "https://drive.google.com/file/d/17MtedLGS1vsw7f6uannBStABT4eVSOV0/view?usp=drive_link" },
  { id: "atma", mr: "आत्मा अंतर्गत बचत गट नोंदणी व प्रशिक्षण", en: "ATMA SHG Registration & Training", emoji: "👥", pdf: "#" },
  { id: "demo", mr: "कृषि व संलग्न क्षेत्राची प्रात्यक्षिके", en: "Agricultural Demonstrations", emoji: "📊", pdf: "#" },
  { id: "pest-mgmt", mr: "एकात्मिक किड / रोग व्यवस्थापन व पीक चिकित्सालय", en: "Integrated Pest/Disease Management & Plant Clinic", emoji: "🩺", pdf: "#" },
  { id: "market", mr: "संकलन एकत्रीकरण केंद्र व विक्री केंद्र", en: "Collection & Marketing Center", emoji: "🏪", pdf: "#" },
  { id: "cold-storage", mr: "कोल्ड स्टोरेज, शीतगृह व शितसाखळी आधुनिकीकरण", en: "Cold Storage & Cold Chain Modernization", emoji: "❄️", pdf: "#" },
  { id: "onion", mr: "कांदा चाळ बांधकाम (राफअ व मग्रारोहयो)", en: "Onion Storage Structure Construction", emoji: "🧅", pdf: "#" },
  { id: "forestry", mr: "वृक्ष लागवड (वनशेती)", en: "Tree Plantation (Agroforestry)", emoji: "🌲", pdf: "#" },
  { id: "licenses", mr: "बियाणे खते कीटकनाशके विक्री परवाने", en: "Seed, Fertilizer & Pesticide Licenses", emoji: "🏷️", pdf: "#" },
  { id: "cropsap", mr: "CROPSAP व HORTSAP पिकावरील कीड सर्वेक्षण", en: "CROPSAP & HORTSAP Pest Surveillance", emoji: "🔍", pdf: "#" },
  { id: "magazine", mr: "शेतकरी मासिक व कृषिदर्शनी २०२५", en: "Farmer Magazine & Krushidarshani", emoji: "📖", pdf: "#" },
  { id: "soil", mr: "माती नमुने तपासणी व मृद आरोग्य सुपिकता", en: "Soil Testing & Soil Health Card", emoji: "🧪", pdf: "#" },
  { id: "awards", mr: "कृषी विषयक पुरस्कार", en: "Agricultural Awards", emoji: "🏅", pdf: "#" },
  { id: "hort-mission", mr: "राष्ट्रीय फलोत्पादन अभियान व इतर राष्ट्रीय अभियान", en: "National Horticulture Mission & Other Missions", emoji: "🍈", pdf: "#" },
  { id: "micro-irr", mr: "सूक्ष्म सिंचन संच वितरक नोंदणी (PMKSY)", en: "Micro Irrigation Dealer Registration (PMKSY)", emoji: "🚰", pdf: "#" },
  { id: "daesi", mr: "कृषी निविष्ठा विक्रेते पदविका अभ्यासक्रम (DAESI)", en: "DAESI Diploma for Agricultural Input Dealers", emoji: "📜", pdf: "#" },
  { id: "fpo", mr: "शेतकरी उत्पादक कंपनी (FPO) स्थापना व अर्थसहाय्य", en: "FPO Establishment & Financial Assistance", emoji: "🤝", pdf: "#" },
  { id: "crop-cutting", mr: "पीक कापणी प्रयोग मार्गदर्शिका", en: "Crop Cutting Experiment Guidelines", emoji: "📐", pdf: "#" },
  { id: "adarsh-gaon", mr: "आदर्श गाव योजना", en: "Adarsh Gaon Yojana", emoji: "🏘️", pdf: "#" },
  { id: "pocra-seed", mr: "पोकरा अंतर्गत बीजोत्पादन अनुदान", en: "PoCRA Seed Production Subsidy", emoji: "🌱", pdf: "#" },
  { id: "solar-pump", mr: "मुख्यमंत्री सौर कृषी पंप योजना", en: "Chief Minister Solar Agriculture Pump Scheme", emoji: "☀️", pdf: "#" },
  { id: "gram-samiti", mr: "ग्राम कृषी विकास समिती स्थापना", en: "Gram Krishi Vikas Samiti Establishment", emoji: "🏛️", pdf: "#" },
  { id: "cotton-soy", mr: "कापूस आणि सोयाबीन उत्पादकता वाढ योजना", en: "Cotton & Soybean Productivity Enhancement Scheme", emoji: "🌿", pdf: "#" },
  { id: "backyard", mr: "आदिवासी कुटुंबाच्या परसबागेत फळझाडे लागवड", en: "Tribal Backyard Fruit Orchard Plantation", emoji: "🏡", pdf: "#" },
  { id: "mahavedh", mr: "महावेध प्रकल्प व हवामान अंदाज", en: "Mahavedh Project & Weather Forecast", emoji: "⛅", pdf: "#" },
  { id: "disaster", mr: "नैसर्गिक आपत्ती मदत व किमान आधारभूत किमती (MSP)", en: "Natural Calamity Relief & MSP", emoji: "⚖️", pdf: "#" },
  { id: "soil-water", mr: "मृद व जलसंधारण बाबत शासन निर्णय", en: "Soil & Water Conservation GRs", emoji: "🌊", pdf: "#" },
  { id: "ranbhaji", mr: "रानभाजी महोत्सव", en: "Wild Vegetable Festival (Ranbhaji Mahotsav)", emoji: "🥗", pdf: "#" }
];